CREATE TABLE IF NOT EXISTS AbilityHighlightsPanel_ExperienceModifiers (
  BuildingType    TEXT NOT NULL,
  UnitAbilityType TEXT NOT NULL,
  PRIMARY KEY (BuildingType)
);

INSERT INTO AbilityHighlightsPanel_ExperienceModifiers (BuildingType, UnitAbilityType) VALUES
  ('BUILDING_BARRACKS',           'ABILITY_BARRACKS_TRAINED_UNIT_XP'),
  ('BUILDING_BASILIKOI_PAIDES',   'ABILITY_BASILIKOI_TRAINED_UNIT_XP'),
  ('BUILDING_STABLE',             'ABILITY_STABLE_TRAINED_UNIT_XP'),
  ('BUILDING_ORDU',               'ABILITY_ORDU_TRAINED_UNIT_XP'),
  ('BUILDING_ARMORY',             'ABILITY_ARMORY_TRAINED_UNIT_XP'),
  ('BUILDING_MILITARY_ACADEMY',   'ABILITY_MILITARY_ACADEMY_TRAINED_UNIT_XP'),
  ('BUILDING_LIGHTHOUSE',         'ABILITY_LIGHTHOUSE_TRAINED_UNIT_XP'),
  ('BUILDING_SHIPYARD',           'ABILITY_SHIPYARD_TRAINED_UNIT_XP'),
  ('BUILDING_SEAPORT',            'ABILITY_SEAPORT_TRAINED_UNIT_XP'),
  ('BUILDING_HANGAR',             'ABILITY_HANGAR_TRAINED_AIRCRAFT_XP'),
  ('BUILDING_AIRPORT',            'ABILITY_AIRPORT_TRAINED_AIRCRAFT_XP');
